# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 627)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777188))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../main.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 16px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Source_text = QtWidgets.QTextEdit(self.centralwidget)
        self.Source_text.setGeometry(QtCore.QRect(0, 30, 751, 281))
        self.Source_text.setStyleSheet("QTextEdit {\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        background: rgb(255, 255, 255);\n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;\n"
"    font:20px;    \n"
"}\n"
"")
        self.Source_text.setObjectName("Source_text")
        self.encode_type = QtWidgets.QComboBox(self.centralwidget)
        self.encode_type.setGeometry(QtCore.QRect(122, 315, 111, 26))
        self.encode_type.setStyleSheet("QComboBox {\n"
"    /* 边框宽度,线条样式,颜色 */\n"
"    border:1px solid black;\n"
"\n"
"    /* 倒角 */\n"
"    border-radius:5px;\n"
"\n"
"    /* 内边框 */\n"
"    padding:1px 10px 1px 3px;\n"
"\n"
"    min-width:10px;\n"
"}\n"
"QComboBox:editable {\n"
"    background:green;\n"
"}\n"
"/* 当下拉框打开时, 移动显示框文本位置*/\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"/* 下拉按钮 */\n"
"QComboBox::drop-down {\n"
"\n"
"    subcontrol-origin: padding;\n"
"\n"
"    /* 按钮位置,右上角 */\n"
"    subcontrol-position: top right;\n"
"   /* 一条边框线控制 */\n"
"    border-left-width: 1px;\n"
"    border-left-color: black;\n"
"    border-left-style: solid;\n"
"    width: 18px;\n"
"}\n"
"/* 下拉按钮位移 */\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"/* 下拉列表里的颜色 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: green;\n"
"}\n"
"\n"
"\n"
"")
        self.encode_type.setObjectName("encode_type")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.encode_type.addItem("")
        self.Result_text = QtWidgets.QTextEdit(self.centralwidget)
        self.Result_text.setGeometry(QtCore.QRect(0, 345, 751, 281))
        self.Result_text.setStyleSheet("QTextEdit {\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        background: rgb(255, 255, 255);\n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;\n"
"    font:20px;    \n"
"}\n"
"")
        self.Result_text.setObjectName("Result_text")
        self.source = QtWidgets.QLabel(self.centralwidget)
        self.source.setGeometry(QtCore.QRect(6, 9, 72, 15))
        self.source.setStyleSheet("    /* 前景色 */  \n"
"    color:green;  \n"
"   font:bold 20px;  ")
        self.source.setObjectName("source")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(7, 317, 72, 21))
        self.result.setStyleSheet("    /* 前景色 */  \n"
"    color:green;  \n"
"   font:bold 20px;  ")
        self.result.setObjectName("result")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(758, 3, 114, 183))
        self.groupBox.setStyleSheet("    /* 前景色 */  \n"
"    color:rgb(170, 0, 255)\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(10, 20, 93, 154))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.panduan = QtWidgets.QPushButton(self.splitter_3)
        self.panduan.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.panduan.setObjectName("panduan")
        self.chaxunliehshu = QtWidgets.QPushButton(self.splitter_3)
        self.chaxunliehshu.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.chaxunliehshu.setObjectName("chaxunliehshu")
        self.user = QtWidgets.QPushButton(self.splitter_3)
        self.user.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.user.setObjectName("user")
        self.version = QtWidgets.QPushButton(self.splitter_3)
        self.version.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.version.setObjectName("version")
        self.path = QtWidgets.QPushButton(self.splitter_3)
        self.path.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.path.setObjectName("path")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(758, 185, 114, 245))
        self.groupBox_3.setStyleSheet("    /* 前景色 */  \n"
"    color:rgb(170, 0, 255)\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.splitter_4 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_4.setGeometry(QtCore.QRect(10, 20, 93, 218))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.single_databases = QtWidgets.QPushButton(self.splitter_4)
        self.single_databases.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.single_databases.setObjectName("single_databases")
        self.current_databases = QtWidgets.QPushButton(self.splitter_4)
        self.current_databases.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.current_databases.setObjectName("current_databases")
        self.all_databases = QtWidgets.QPushButton(self.splitter_4)
        self.all_databases.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.all_databases.setObjectName("all_databases")
        self.single_tables = QtWidgets.QPushButton(self.splitter_4)
        self.single_tables.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.single_tables.setObjectName("single_tables")
        self.all_tables = QtWidgets.QPushButton(self.splitter_4)
        self.all_tables.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.all_tables.setObjectName("all_tables")
        self.single_columns = QtWidgets.QPushButton(self.splitter_4)
        self.single_columns.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.single_columns.setObjectName("single_columns")
        self.all_columns = QtWidgets.QPushButton(self.splitter_4)
        self.all_columns.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.all_columns.setObjectName("all_columns")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(758, 545, 114, 81))
        self.groupBox_9.setStyleSheet("    /* 前景色 */  \n"
"    color:rgb(170, 0, 255)\n"
"")
        self.groupBox_9.setObjectName("groupBox_9")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_9)
        self.splitter_2.setGeometry(QtCore.QRect(10, 20, 93, 58))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.data = QtWidgets.QPushButton(self.splitter_2)
        self.data.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.data.setObjectName("data")
        self.others = QtWidgets.QPushButton(self.splitter_2)
        self.others.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.others.setObjectName("others")
        self.sql_type = QtWidgets.QComboBox(self.centralwidget)
        self.sql_type.setGeometry(QtCore.QRect(660, 4, 91, 24))
        self.sql_type.setStyleSheet("QComboBox {\n"
"    /* 边框宽度,线条样式,颜色 */\n"
"    border:1px solid black;\n"
"\n"
"    /* 倒角 */\n"
"    border-radius:5px;\n"
"\n"
"    /* 内边框 */\n"
"    padding:1px 10px 1px 3px;\n"
"\n"
"    min-width:10px;\n"
"}\n"
"QComboBox:editable {\n"
"    background:green;\n"
"}\n"
"/* 当下拉框打开时, 移动显示框文本位置*/\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"/* 下拉按钮 */\n"
"QComboBox::drop-down {\n"
"\n"
"    subcontrol-origin: padding;\n"
"\n"
"    /* 按钮位置,右上角 */\n"
"    subcontrol-position: top right;\n"
"   /* 一条边框线控制 */\n"
"    border-left-width: 1px;\n"
"    border-left-color: black;\n"
"    border-left-style: solid;\n"
"    width: 18px;\n"
"}\n"
"/* 下拉按钮位移 */\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"/* 下拉列表里的颜色 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: green;\n"
"}\n"
"\n"
"\n"
"")
        self.sql_type.setObjectName("sql_type")
        self.sql_type.addItem("")
        self.sql_type.addItem("")
        self.sql_type.addItem("")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(100, 6, 151, 20))
        self.time.setStyleSheet("    /* 前景色 */  \n"
"    color:green;  ")
        self.time.setObjectName("time")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(241, 314, 511, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.encode_Button = QtWidgets.QPushButton(self.splitter)
        self.encode_Button.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 16px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.encode_Button.setObjectName("encode_Button")
        self.decode_Button = QtWidgets.QPushButton(self.splitter)
        self.decode_Button.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 16px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.decode_Button.setObjectName("decode_Button")
        self.clear_Button = QtWidgets.QPushButton(self.splitter)
        self.clear_Button.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.clear_Button.setObjectName("clear_Button")
        self.Copy_Source_Button = QtWidgets.QPushButton(self.splitter)
        self.Copy_Source_Button.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.Copy_Source_Button.setObjectName("Copy_Source_Button")
        self.Copy_ResultButton = QtWidgets.QPushButton(self.splitter)
        self.Copy_ResultButton.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.Copy_ResultButton.setObjectName("Copy_ResultButton")
        self.tihuan_source = QtWidgets.QLineEdit(self.centralwidget)
        self.tihuan_source.setGeometry(QtCore.QRect(290, 2, 113, 27))
        self.tihuan_source.setStyleSheet("QLineEdit {\n"
"        border-radius: 4px;\n"
"        height: 25px;\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(255, 255, 255)\n"
"}\n"
"QLineEdit:enabled {\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QLineEdit:enabled:hover, QLineEdit:enabled:focus {\n"
"        color: rgb(255, 85, 255)\n"
"}\n"
"QLineEdit:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}")
        self.tihuan_source.setObjectName("tihuan_source")
        self.tihuan_result = QtWidgets.QLineEdit(self.centralwidget)
        self.tihuan_result.setGeometry(QtCore.QRect(461, 2, 113, 27))
        self.tihuan_result.setStyleSheet("QLineEdit {\n"
"        border-radius: 4px;\n"
"        height: 25px;\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(255, 255, 255)\n"
"}\n"
"QLineEdit:enabled {\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QLineEdit:enabled:hover, QLineEdit:enabled:focus {\n"
"        color:rgb(255, 85, 255)\n"
"}\n"
"QLineEdit:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}")
        self.tihuan_result.setObjectName("tihuan_result")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(407, 4, 51, 24))
        self.label2.setStyleSheet("    /* 前景色 */  \n"
"    color:green;  \n"
"   font: 17px;  ")
        self.label2.setObjectName("label2")
        self.tihuan = QtWidgets.QPushButton(self.centralwidget)
        self.tihuan.setGeometry(QtCore.QRect(581, 3, 71, 27))
        self.tihuan.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.tihuan.setObjectName("tihuan")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(270, 4, 21, 24))
        self.label3.setStyleSheet("    /* 前景色 */  \n"
"    color:green;  \n"
"   font: 17px;  ")
        self.label3.setObjectName("label3")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(758, 430, 114, 115))
        self.groupBox_10.setStyleSheet("    /* 前景色 */  \n"
"    color:rgb(170, 0, 255)\n"
"")
        self.groupBox_10.setObjectName("groupBox_10")
        self.splitter_7 = QtWidgets.QSplitter(self.groupBox_10)
        self.splitter_7.setGeometry(QtCore.QRect(10, 20, 93, 90))
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.mangzhu_databases = QtWidgets.QPushButton(self.splitter_7)
        self.mangzhu_databases.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.mangzhu_databases.setObjectName("mangzhu_databases")
        self.mangzhu_tables = QtWidgets.QPushButton(self.splitter_7)
        self.mangzhu_tables.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.mangzhu_tables.setObjectName("mangzhu_tables")
        self.mangzhu_lumns = QtWidgets.QPushButton(self.splitter_7)
        self.mangzhu_lumns.setStyleSheet("QPushButton\n"
"{  \n"
"    /* 前景色 */  \n"
"    color:green;  \n"
" \n"
"    /* 背景色 */  \n"
"    background-color:rgb(223,223,223);  \n"
" \n"
"    /* 边框风格 */  \n"
"    border-style:outset;  \n"
" \n"
"    /* 边框宽度 */  \n"
"    border-width:0.5px;  \n"
" \n"
"    /* 边框颜色 */  \n"
"    border-color:rgb(10,45,110);  \n"
" \n"
"    /* 边框倒角 */  \n"
"    border-radius:5px;  \n"
" \n"
"    /* 字体 */  \n"
"    font:bold 14px;  \n"
"  \n"
" \n"
"    /* 内边距 */  \n"
"    padding:4px;  \n"
"} \n"
" \n"
"/* 鼠标按下时的效果 */ \n"
"QPushButton#pushButton:pressed \n"
"{  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(40,85,20);  \n"
" \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
" \n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;  \n"
"    padding-top:6px;  \n"
"}\n"
" \n"
"/* 按钮样式 */ \n"
"QPushButton:flat \n"
"{  \n"
"    border:2px solid red;  \n"
"} \n"
" \n"
"/*鼠标悬浮时的效果*/\n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:8px;\n"
"    padding-top:8px;\n"
"}")
        self.mangzhu_lumns.setObjectName("mangzhu_lumns")
        self.groupBox.raise_()
        self.Source_text.raise_()
        self.encode_type.raise_()
        self.Result_text.raise_()
        self.source.raise_()
        self.result.raise_()
        self.splitter.raise_()
        self.groupBox_3.raise_()
        self.groupBox_9.raise_()
        self.sql_type.raise_()
        self.time.raise_()
        self.tihuan_source.raise_()
        self.tihuan_result.raise_()
        self.label2.raise_()
        self.tihuan.raise_()
        self.label3.raise_()
        self.groupBox_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SQL Injection Assistant  By qianxiao996  Blog: https://blog.qianxiao996.cn"))
        self.encode_type.setItemText(0, _translate("MainWindow", "URL-UTF8"))
        self.encode_type.setItemText(1, _translate("MainWindow", "URL-GB2312"))
        self.encode_type.setItemText(2, _translate("MainWindow", "Unicode"))
        self.encode_type.setItemText(3, _translate("MainWindow", "Escape(%U)"))
        self.encode_type.setItemText(4, _translate("MainWindow", "HtmlEncode"))
        self.encode_type.setItemText(5, _translate("MainWindow", "ASCII"))
        self.encode_type.setItemText(6, _translate("MainWindow", "Base64"))
        self.encode_type.setItemText(7, _translate("MainWindow", "Str<->Hex"))
        self.encode_type.setItemText(8, _translate("MainWindow", "SQL-Char"))
        self.encode_type.setItemText(9, _translate("MainWindow", "SQL-Hex"))
        self.source.setText(_translate("MainWindow", "Source："))
        self.result.setText(_translate("MainWindow", "Result"))
        self.groupBox.setTitle(_translate("MainWindow", "Public"))
        self.panduan.setText(_translate("MainWindow", "判断注入"))
        self.chaxunliehshu.setText(_translate("MainWindow", "查询列数"))
        self.user.setText(_translate("MainWindow", "查询用户"))
        self.version.setText(_translate("MainWindow", "查询版本"))
        self.path.setText(_translate("MainWindow", "查询库路径"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Order"))
        self.single_databases.setText(_translate("MainWindow", "查询单库"))
        self.current_databases.setText(_translate("MainWindow", "查询当前库"))
        self.all_databases.setText(_translate("MainWindow", "查询所有库"))
        self.single_tables.setText(_translate("MainWindow", "查询单表"))
        self.all_tables.setText(_translate("MainWindow", "查询所有表"))
        self.single_columns.setText(_translate("MainWindow", "查询单列"))
        self.all_columns.setText(_translate("MainWindow", "查询所有列"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Other"))
        self.data.setText(_translate("MainWindow", "查询数据"))
        self.others.setText(_translate("MainWindow", "Others"))
        self.sql_type.setItemText(0, _translate("MainWindow", "MYSQL"))
        self.sql_type.setItemText(1, _translate("MainWindow", "MSSQL"))
        self.sql_type.setItemText(2, _translate("MainWindow", "ORACLE"))
        self.time.setText(_translate("MainWindow", "Time"))
        self.encode_Button.setText(_translate("MainWindow", "Encode"))
        self.decode_Button.setText(_translate("MainWindow", "Decode"))
        self.clear_Button.setText(_translate("MainWindow", "Clear"))
        self.Copy_Source_Button.setText(_translate("MainWindow", "Copy_Source"))
        self.Copy_ResultButton.setText(_translate("MainWindow", "Copy_Result"))
        self.label2.setText(_translate("MainWindow", "替换为"))
        self.tihuan.setText(_translate("MainWindow", "替 换"))
        self.label3.setText(_translate("MainWindow", "将"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Blinds"))
        self.mangzhu_databases.setText(_translate("MainWindow", "盲注查库"))
        self.mangzhu_tables.setText(_translate("MainWindow", "盲注查表"))
        self.mangzhu_lumns.setText(_translate("MainWindow", "盲注查列"))

